{% set name = "metaphone" %}
{% set version = "0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name[0]|upper }}{{ name[1:] }}-{{ version }}.tar.gz
  sha256: ad0beadca66cb7ec6ede71ef72bb02da097c493ddf159930d6340bc83f53da27
  patches:
    - patches/0001-assertEqual-over-deprecated-assertEquals.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - patch       # [not win]
    - m2-patch    # [win]
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - metaphone
  requires:
    - pip
    - pytest
  source_files:
    - metaphone/tests
  commands:
    - pip check
    # ignore these tests, they fail probably because of unicode / utf8
    - pytest metaphone/tests --ignore metaphone/tests/test_word.py

about:
  home: https://github.com/oubiwann/metaphone
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A Python implementation of the double metaphone algorithms
  description: A Python implementation of the Metaphone and Double Metaphone algorithms
  doc_url: https://github.com/oubiwann/metaphone?tab=readme-ov-file#metaphone
  dev_url: https://github.com/oubiwann/metaphone

extra:
  recipe-maintainers:
    - wyseguy7
    - ericdill
    - marshall245
