travis:
  secure:
    BINSTAR_TOKEN: n9iaYZ6hRsUoPCVw0AQyyAvWEOjaiHonqysElqyI5gR3gX2odBjhg6N5u5hdYobVXIFH3jKcz2sL/jNox0bCbVruPwJeKeUdZ6RQlVVSTcaoVU5HWrbqvNzSlVctWQtm71b6AvkhJydsc1mEYS4WyQx+1YTw3UHNNFeVAE+GVVVL1UpgB08zvsfC7rNNKFwDW8No3u9nh/b1DELxHXI3eHT8R6wN7rbH6z+VAzvVCyZ8lmXjvgkYLy6TbDge5k/+A4tCd3Q2S2Hx8Q8CdzzE1t+gjLx7QsYC8fqMMQQFKytGokVfQUG2A8LlXRGSEB7Ty3YPNS/WSLSJuB200To5Vdo5vwrlYnEG73Pa54YoSj2Q1fQuefY8f1DeBHLcdmbTCgnXZVfBlUr6pIxOnJqKYGppx35TAmq/nlicj03QnhG7c69muSEmHhs/YXi4Ad3JrC9wQ+URix1aklx5QMS0Us3ajuLUYL0bc+ffQyFceYBu1GPKp/DtkpAQOv/x4bHGO9eFm+a8CpchDrQkPlrSCvU/Wksfc7AbJNX5uC/kZdSSP9q+zmIskzaQzqhx0Dzvl2o8VZ8KzFNGu1K37MCSwyQf/5brsmHfbt5J69bQvfSP2wiqlIICWXF0mqBEl5KHEMmj0+qyQJA6n3bw6FbbrPGUH5MW7pRcdU/R57F2N64=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
