travis:
  secure:
    BINSTAR_TOKEN: kaPNgoLig83XzJ8lzm3TACivKRsG1hqsJWJ63bFZAMubgrOT647a2O4y2tu3J/93I3j0tmrKlV+qMQvrFQ1i4ydx/kpOIp2jH9xF0/XvtoCkbRQw0G6PZoNMCNUJxgyQEhc+C9+wmgL51JTSr2lxBBsP8oG30+Kq8bGo9VMxuSX9kLQNBkhF8SUxIlpG7focSyB30L01bCvPIeg0k8D8fqNWJ/wR9fMW9nmIVoktqG3/iWkEN1qUAvS/dxZO/IHhsW4KZLG6gYug0Lov02tTuysCzwro3c7Ar9jVuA/LESxxxb0Z0WhBZMiJF9d1eCK+Cp6nQ+tKwfCZbgk02V+JfKV6pLt8ax7jTAfcOqZ3oxpWrAHniZA7AHudicy+J6yUbzvLes3r0XeyVIlhY+KxadvUxYtVE7es9zePf0g1qXMfQZul4hYQzYFlUjwb3GQyNxM8ZJVREz4AWOns0ad/6j2V4QXS4MTq2FIU67NffCepX5KAS56Iiwepa7RkeG9T0MzFWRrEL91cM3Ziw7PVY2HkFBFf8bi2m+Ieb8wqZGApGWEU3g+LjYqQvzqI/IUDE9qyATz2Co06VZtKR44BCEtC42vLLrqTc6gTqepVtZMzKdJRd2NoD/4HP4whMmbn9Hoj335Kl4d+MnvD52j2gP28EirjNzs8acx5/1Bl+UY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
